const ACTION_TYPES = {
  REST_LOADING: "REST_LOADING",
  REST_SUCCESS: "REST_SUCCESS",
  REST_ERROR: "REST_ERROR",

  BASKET_LOADING: "BASKET_LOADING",
  BASKET_SUCCESS: "BASKET_SUCCESS",
  BASKET_ERROR: "BASKET_ERROR",
  CREATE_ITEM: "CREATE_ITEM",
  UPDATE_ITEM: "UPDATE_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
};

export default ACTION_TYPES;
